### PR TITLE
support macos

### PR DESCRIPTION
**Pull request by zouguangxian**

### CODE REVIEW

**Comment by skalle** [comment]
Hey Zou. 

Exciting stuff!.

**Comment by zouguangxian** [comment]
> @googlebot I signed it!

**Comment by skalle** [comment]
Thx. a lot for that addition! .

**Comment by skalle** [comment]
Hey Zou. Ran into some problems with the Circle CI tests. 

Have to revert until we have those under control.

===
#!/bin/bash -eo pipefail
go test -v ./...

# github.com/google/goterm/term
term/termios.go:302:34: undefined: syscall.TIOCPTYGNAME
term/termios.go:304:65: undefined: syscall.TIOCPTYGNAME
term/termios.go:389:85: undefined: syscall.TIOCPTYUNLK
term/termios.go:394:77: undefined: syscall.TIOCPTYGRANT
# github.com/google/goterm/term [github.com/google/goterm/term.test]
term/termios.go:302:34: undefined: syscall.TIOCPTYGNAME
term/termios.go:304:65: undefined: syscall.TIOCPTYGNAME
term/termios.go:389:85: undefined: syscall.TIOCPTYUNLK
term/termios.go:394:77: undefined: syscall.TIOCPTYGRANT
FAIL	github.com/google/goterm/term [build failed]

Exited with code exit status 2

CircleCI received exit code 2

**Comment by skalle** [comment]
Hey zouguangxian@ are you sorting out the tests for this PR? 

You could use Conditional Compiling to split the linux and MacOS tests.
Eg. http://blog.ralch.com/tutorial/golang-conditional-compilation/

I'd love to have MacOS support for GoTerm , if you don't have the cycles I'll try to find some cycles to sort out the tests. With your permission ofcourse.

**Comment by zouguangxian** [comment]
Hey @skalle, Yes, you can fully control the code, I'm glad you have the cycles to do fix it.

**Pull request merged**
